In [1]:
import os
os.chdir("C:/Users/lohitha ramya kone/Desktop/remote internship 2020/data sets")
os.getcwd()

'C:\\Users\\lohitha ramya kone\\Desktop\\remote internship 2020\\data sets'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('kindle_reviews.csv', encoding = "ISO-8859-1",nrows=50000)

In [4]:
df

,Unnamed: 0,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,B000F83SZQ,"[0, 0]",5,I enjoy vintage books and movies so I enjoyed ...,"05 5, 2014",A1F6404F1VG29J,Avidreader,Nice vintage story,1399248000
1,1,B000F83SZQ,"[2, 2]",4,This book is a reissue of an old one; the auth...,"01 6, 2014",AN0N05A9LIJEQ,critters,Different...,1388966400
2,2,B000F83SZQ,"[2, 2]",4,This was a fairly interesting read. It had ol...,"04 4, 2014",A795DMNCJILA6,dot,Oldie,1396569600
3,3,B000F83SZQ,"[1, 1]",5,I'd never read any of the Amy Brewster mysteri...,"02 19, 2014",A1FV0SX13TWVXQ,"Elaine H. Turley ""Montana Songbird""",I really liked it.,1392768000
4,4,B000F83SZQ,"[0, 1]",4,"If you like period pieces - clothing, lingo, y...","03 19, 2014",A3SPTOKDG7WBLN,Father Dowling Fan,Period Mystery,1395187200
...,...,...,...,...,...,...,...,...,...,...
49995,49995,B004PLNP2K,"[0, 0]",5,Anne Marie Novark has done it again. Book 3 in...,"05 27, 2013",A3P31Y2T3HBUS6,Jobanga,A Match Made In Texas,1369612800
49996,49996,B004PLNP2K,"[0, 0]",4,This goes to show just how much hurt losing yo...,"05 17, 2013",A1CPJD87PMPJQJ,KareBear1965,worth the time and money,1368748800
49997,49997,B004PLNP2K,"[0, 0]",4,Despite the physical beauty of Novark's charac...,"03 30, 2014",A1K1P8Y3LO20AZ,K. Pilon,I'm a sucker for a sensitive handsome man,1396137600
49998,49998,B004PLNP2K,"[0, 0]",4,"I have enjoyed this series, and will continue ...","08 16, 2013",AK3MABTV8TK8M,"lcj ""jcl623""",Not the best in the series....,1376611200
49999,49999,B004PLNP2K,"[0, 0]",4,This book follows along similar guidelines as ...,"10 27, 2013",AI8JBNTZHEPZJ,Lily,A match Made In Texas,1382832000